<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
      <UserSecretsId>1fcea60b-dd2a-44a0-8d56-4d0ae28e2e91</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Azure.Identity" Version="1.21.0" />
      <PackageReference Include="Azure.Storage.Blobs" Version="12.29.2" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.22">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.22" />
      <PackageReference Include="Microsoft.Identity.Web" Version="3.14.1" />
    </ItemGroup>

</Project>
